folders:
  srv: "./srv"
typer:
  strictPropertyInitialization: false
  strictNullChecks: false
  allowArbitraryExtensions: true
log:
  levels:
    sql: error
    cds: info
    odata: info
requires:
  auth:
    kind: ias
  grant-mcp:
    kind: rest
    credentials:
      destination: grant-mcp
  
  destinations: true
features:
  toggles:
    auth: true
  "[production]":
    emulate_vcap_services: true
