folders:
  srv: "./srv"
typer:
  strictPropertyInitialization: false
  strictNullChecks: false
  allowArbitraryExtensions: true
log:
  levels:
    sql: error
    cds: info
    odata: info
requires:
  auth:
    kind: ias
  db:
    kind: sqlite
    credentials:
      url: db.sqlite
  grant-mcp:
    kind: rest
    credentials:
      destination: grant-mcp
  
  destinations: true
  "[development]":
    db:
      kind: sqlite
      credentials:
        url: db.sqlite
    auth:
      kind: mocked
      users:
        alice:
          tenant: t1
          roles:
            - grant_management_create
            - grant_management_update
            - grant_management_replace
            - grant_management_revoke
            - grant_management_query
        bob:
          tenant: t2
          roles:
            - grant_management_create
            - grant_management_update
            - grant_management_replace
            - grant_management_revoke
            - grant_management_query
features:
  toggles:
    auth: true
  "[production]":
    emulate_vcap_services": true
