apiVersion: apps/v1
kind: Deployment

metadata:
  name: grant-management
  namespace: grant-managment-dev

  labels:
    app: grant-management
    version: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grant-management
  template:
    metadata:
      labels:
        app: grant-management
        version: latest
    spec:
      containers:
      - name: grant-management
        image: scai-dev.common.repositories.cloud.sap/grant-management:latest
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: NODE_ENV
          value: "production"
      imagePullSecrets:
      - name: docker-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: grant-management-service
  namespace: grant-managment-dev
  labels:
    app: grant-management
spec:
  selector:
    app: grant-management
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: grant-management-api-rule
  namespace: grant-managment-dev
  labels:
    app: grant-management
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: grants
  service:
    name: grant-management-service
    port: 80
  rules:
    - path: /.*
      methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"]
      accessStrategies:
        - handler: noop
      mutators:
        - handler: noop
