#!/bin/bash
#
# Generate env/kube.env from current kubectl context and a new ServiceAccount token.
# Run from repo root. Requires kubectl and an existing cluster context.
#
# Usage: ./scripts/generate-kube-env.sh [OPTIONS]
#

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/env/kube.env"
DURATION="${KUBE_TOKEN_DURATION:-24h}"

mkdir -p "$REPO_ROOT/env"

# Get cluster server from current context
KUBE_SERVER=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}' 2>/dev/null) || true
if [ -z "$KUBE_SERVER" ]; then
  echo "Error: No cluster in current kubectl context. Run: kubectl config use-context <context>" >&2
  exit 1
fi

# Generate token (outputs env vars)
echo "Creating ServiceAccount token (duration: $DURATION)..."
ENV_OUTPUT=$("$SCRIPT_DIR/create-serviceaccount-token.sh" --duration "$DURATION" --output env)
eval "$ENV_OUTPUT"

# Write env file (no token in example; real token in kube.env)
{
  echo "# Generated by scripts/generate-kube-env.sh - do not commit if it contains KUBE_TOKEN"
  echo "KUBE_SERVER=$KUBE_SERVER"
  echo "KUBE_NAMESPACE=$KUBE_NAMESPACE"
  echo "KUBE_SERVICE_ACCOUNT=$KUBE_SERVICE_ACCOUNT"
  echo "KUBE_TOKEN=$KUBE_TOKEN"
} > "$ENV_FILE"

echo "Wrote $ENV_FILE"
echo "Source it: source env/kube.env"
echo "Then use: ./scripts/install-kubectl-and-login.sh (or ensure KUBECONFIG is set)"
