FROM sapse/approuter:20.8.0

COPY auth/ auth/
COPY api-docs/ api-docs/
COPY xs-app.json .


# # Install Oh My Zsh
# RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# # Set Zsh as the default shell
# RUN chsh -s /usr/bin/zsh
# CMD ["zsh"]
    

