version: "3.8"

services:
  mcp-proxy:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MCP_SERVER_URL=http://mcp-server:3000/mcp
      - AUTH_SERVER_URL=http://host.docker.internal:4004/oauth-server
      - GRANT_MANAGEMENT_URL=http://host.docker.internal:4004/grants-management
      - MCP_CLIENT_ID=mcp-agent-client
      - BASE_URL=http://localhost:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); })",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
