version: "3.8"

services:
  oauth-grant-management:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - oauth-grant-management-node-modules:/workspace/node_modules
      - oauth-grant-management-deno-cache:/workspace/.deno
    ports:
      - "3000:3000" # React Router Dev Server
      - "4004:4004" # CDS OData Service
      - "5173:5173" # Vite Dev Server
      - "8080:8080" # Production Server
    environment:
      - NODE_ENV=development
      - CDS_ENV=development
      - DENO_DIR=/workspace/.deno
    command: sleep infinity
    networks:
      - oauth-grant-management-network

  # Optional: SQLite database service for shared development
  sqlite-db:
    image: alpine:latest
    volumes:
      - oauth-grant-management-db:/data
    command: sh -c "apk add --no-cache sqlite && sleep infinity"
    networks:
      - oauth-grant-management-network

volumes:
  oauth-grant-management-node-modules:
  oauth-grant-management-deno-cache:
  oauth-grant-management-db:

networks:
  oauth-grant-management-network:
    driver: bridge
